services:
  backend:
    build: ./backend
    volumes:
      - ./XGB_Models:/models:ro
    environment:
      - MODEL_DIR=/models
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:8001
    ports:
      - "3000:80"
    depends_on:
      - backend
