export { default as PTable, type PTableProps } from './PTable.vue'
export { default as PTableHeader, type PTableHeaderProps } from './PTableHeader.vue'
export { default as PTableHead, type PTableHeadProps, type PTableHeadEmits } from './PTableHead.vue'
export { default as PTableCell, type PTableCellProps, type PTableCellEmits } from './PTableCell.vue'
export { default as PTableRow, type PTableRowProps } from './PTableRow.vue'
export { default as PTableBody, type PTableBodyProps } from './PTableBody.vue'
export { default as PTableEmpty, type PTableEmptyProps } from './PTableEmpty.vue'
export { default as PTableFooter, type PTableFooterProps } from './PTableFooter.vue'
export { default as PTableCaption, type PTableCaptionProps } from './PTableCaption.vue'